3rdparty/nuxeo/nuxeo-platform-listener/bampfa/src/main/java/org/collectionspace/services/listener/UpdateArtistDisplayNameListener.java, 3rdparty/nuxeo/nuxeo-platform-listener/bampfa/src/main/java/org/collectionspace/services/listener/UpdateNationalitiesListener.java, 3rdparty/nuxeo/nuxeo-platform-listener/bampfa/src/main/resources/OSGI-INF/ecm-types-contrib.xml, services/batch/service/src/main/java/org/collectionspace/services/batch/nuxeo/UpdateObjectFromPersonsAuthorityBatchJob.java, services/batch/service/src/main/java/org/collectionspace/services/batch/nuxeo/UpdateObjectNationalitiesFromPersonBatchJob.java
- Renamed batch job since both listeners now use it.
=> CC-545: Added updateDisplayNameListener, renamed nationalities batch job

build.properties, services/batch/service/src/main/java/org/collectionspace/services/batch/nuxeo/MergeAuthorityItemsBatchJob.java
=> CC-700: Fixed MergeAuthorityItems batch job to properly handle parameters

3rdparty/nuxeo/nuxeo-platform-listener/bampfa/src/main/java/org/collectionspace/services/listener/UpdateArtistDisplayNameListener.java, 3rdparty/nuxeo/nuxeo-platform-listener/bampfa/src/main/java/org/collectionspace/services/listener/UpdateNationalitiesListener.java
=> CC-820: Added message to identify optimized vs unoptimized listener

services/report/3rdparty/jasper-cs-report/src/main/resources/deprecated/PackingList.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/deprecated/PackingList.xml
Deprecate PackingList report:
Move PackingList.jrxml and PackingList.xml files to new "deprecated" directory
=> CC-1071: deprecate PackingList.jrxml report

services/account/service/src/main/java/org/collectionspace/services/account/AccountResource.java
CC-1384: Added check for null/ghost role value when checking perms to run reports and/or batch jobs.
=> CC-1384: Added check for null/ghost role value.

services/account/service/src/main/java/org/collectionspace/services/account/AccountResource.java, services/account/service/src/main/java/org/collectionspace/services/account/storage/AccountDocumentHandler.java, services/account/service/src/main/java/org/collectionspace/services/account/storage/AccountStorageClient.java, services/authentication/service/src/main/java/org/collectionspace/authentication/spring/CSpaceUserDetailsService.java, services/authentication/service/src/main/java/org/collectionspace/authentication/spring/SpringAuthNContext.java, services/common/src/main/java/org/collectionspace/services/common/SecurityResourceBase.java, services/common/src/main/java/org/collectionspace/services/common/context/RemoteServiceContextImpl.java, services/common/src/main/java/org/collectionspace/services/common/storage/jpa/JpaStorageClientImpl.java
Several fixes that should address the Account corruption during password reset workflow.
=> CC-241: Candidate fix for Account corruption during password reset workflow.

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaExhibitionChecklistGroup.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaExhibitionChecklistGroupSingleArtist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaGroupAccnOtherNumber.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaGroupAccnOtherNumber_artist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaGroupAccnOtherNumber_otherNum.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaGroupCollection.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaGroupCollection_artist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaGroupLocation.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaGroupLocation_artist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaExhibitionChecklistGroup.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaExhibitionChecklistGroupSingleArtist.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaGroupAccnOtherNumber.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaGroupAccnOtherNumber_artist.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaGroupAccnOtherNumber_otherNum.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaGroupCollection.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaGroupCollection_artist.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaGroupLocation.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaGroupLocation_artist.xml
change csid parameter to groupcsid for all group reports.
update resource file to set correct context.
=> CC-1344: Update Group .jrxml and resource files

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/pahma/pahmaGroupNAGPRAexcel.jrxml
Update NAGPRA tablenames and add getdispl function to return displayname instead of refname.
=> CC-1538: update NAGPRA changes

services/IntegrationTests/src/main/resources/log4j2-surefire.xml, services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/authority.xml, services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/contactSubresource.xml, services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/personitemWithContact.xml, services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/personitemWithContact1.xml, services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/personitemWithContact2.xml, services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/res/contactItems.res.xml, services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/res/personItemsWithContact.res.xml, services/authority/service/src/main/java/org/collectionspace/services/common/vocabulary/AuthorityResourceWithContacts.java, services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml, services/contact/service/src/main/java/org/collectionspace/services/contact/nuxeo/ContactValidatorHandler.java
CC-1145: Added code to prevent more than 1 contact per authority term
=> CC-1145: Added code to prevent more than 1 contact per authority term

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/ucbg/ucbgRareStatusGenus.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/ucbg/ucbgVoucherGenus.jrxml
Also removed extraneous joins, updated aliases, etc. in query.
Related to CC-1459 and CC-1468.
=> CC-1696: Update genus reports to use genus instead of taxon name.

services/authorization-mgt/import/build.xml, services/authorization-mgt/import/src/main/java/org/collectionspace/services/authorization/importer/AuthorizationGen.java, services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml, services/config/src/main/resources/service.xsd
CC-1813: Setting up default read-list only perms for the Audit service resources/records.
=> CC-1813: Setting up default read-list only perms for the Audit service resources/records.

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/ucbg/ucbgLabelOrderExcel.jrxml
- Insert two blank columns at the beginning of the spreadsheet labeled "Notes" and "Job".
- Insert blank column between "Species Name" and "Geographic Place Name" labeled "Sci. Name Line 2".
- Change the header "Species Name" to "Sci. Name Line 1"
- If a label is requested for a Rhododendron species, include the Rhododendron subsection in the "Sci. Name Line 2" Column.  Include the word "subsection" in front of the subsection term. For example the cell should read SUBSECTION VIREYA
- Delete columns "County", "State", and "Country".
- Change the header "Province Type" to "Prov."
- Make all text in the spreadsheet uppercase.
=> CC-1845: update query, layout, text format

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/ucbg/ucbgLabelOrderExcel.jrxml
- Insert two blank columns at the beginning of the spreadsheet labeled "Notes" and "Job".
- Insert blank column between "Species Name" and "Geographic Place Name" labeled "Sci. Name Line 2".
- Change the header "Species Name" to "Sci. Name Line 1"
- If a label is requested for a Rhododendron species, include the Rhododendron subsection in the "Sci. Name Line 2" Column.  Include the word "subsection" in front of the subsection term. For example the cell should read SUBSECTION VIREYA
- Delete columns "County", "State", and "Country".
- Change the header "Province Type" to "Prov."
- Make all text in the spreadsheet uppercase.
=> CSC-1845: update query, layout, text format

services/common/src/main/resources/db/postgresql/tenants/ucbg/fnc-public-findhybaffnoauthname-nuxeo_botgarden.sql
CSC-1972: new function findhybaffnoauthname for UCBG Rare Status reports (CSC-1954/1955)
=> CSC-1972: new function findhybaffnoauthname

services/common/src/main/resources/db/postgresql/tenants/ucbg/fnc-public-findhybaffnoauthname-nuxeo_botgarden.sql
CSC-1972ucb: new function findhybaffnoauthname for UCBG Rare Status reports (CSC-1954, CSC-1955)
=> CSC-1972ucb: new function findhybaffnoauthname

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/cinefiles/cinefilesDocDuplicates.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/cinefiles/cinefilesDocMissing.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/cinefiles/cinefilesDocMissing_csv.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/cinefiles/cinefilesDocUrls.jrxml
=> CSC-2153: Adjust logo container size to center logo in landscape reports

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/cinefiles/cinefilesDocDuplicates.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/cinefiles/cinefilesDocMissing.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/cinefiles/cinefilesDocMissing_csv.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/cinefiles/cinefilesDocUrls.jrxml
=> CSC-2153ucb: Adjust logo container size to center logo in landscape reports

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaUOCbyApprovalStatus.jrxml
Update bampfaUOCbyApprovalStatus.jrxml which was mistakenly excluded from PR 351.
=> CSC-2142ucb: update href in bampfaUOCbyApprovalStatus report

services/client/src/main/java/org/collectionspace/services/client/CollectionSpaceClient.java, services/client/src/main/java/org/collectionspace/services/client/test/AbstractAuthorityServiceTest.java, services/hit/client/src/test/java/org/collectionspace/services/client/test/HitAuthRefsTest.java, services/hit/client/src/test/java/org/collectionspace/services/client/test/HitClientTestUtil.java, services/hit/client/src/test/java/org/collectionspace/services/client/test/HitServiceTest.java, services/hit/client/src/test/java/org/collectionspace/services/client/test/OrganizationAuthRefDocsTest.java, services/hit/client/src/test/java/org/collectionspace/services/client/test/PersonAuthRefDocsTest.java, services/hit/jaxb/src/main/resources/hits-common.xsd, services/organization/client/src/test/java/org/collectionspace/services/client/test/OrgAuthorityServiceTest.java
Fixes tests for person, org, and hit services.
=> NOJIRA: Misc test fixes.

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaExhibitionChecklistGroup.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaExhibitionChecklistGroupSingleArtist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/pahma/ExhibitionDesignerReport.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/pahma/ExhibitionInternalByLocation.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/pahma/ExhibitionInternalByObject.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/pahma/GroupWithImages.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/pahma/TombstonePlus.jrxml
Update BAMPFA and PAHMA reports to use get_deplname to add suffix to imagefilepath as needed
=> CSC-2195ucb: Update BAMPFA and PAHMA reports to use get_deplname

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaExhibitionChecklist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaExhibitionChecklistGroupSingleArtist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaExhibitionChecklistSingleArtist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaExhibitionChecklist.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaExhibitionChecklistGroup.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaExhibitionChecklistSingleArtist.xml
add new jrxml and payload files for Exhibition Checklist by Exhibition/CollectionObject relationship.
for all reports: update logos, change imagefilepath to get Thumbnail instead of Medium jpeg.
=> CSC-2269: add/update Exhibition Checklist report jrxml and payload files

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaExhibitionChecklist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaExhibitionChecklistGroupSingleArtist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaExhibitionChecklistSingleArtist.jrxml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaExhibitionChecklist.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaExhibitionChecklistGroup.xml, services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/payloads/bampfaExhibitionChecklistSingleArtist.xml
add new jrxml and payload files for Exhibition Checklist by Exhibition/CollectionObject relationship.
for all reports: update logos, change imagefilepath to get Thumbnail instead of Medium jpeg.
=> CSC-2269ucb: add/update Exhibition Checklist report jrxml and payload files

services/report/3rdparty/jasper-cs-report/src/main/resources/tenants/bampfa/bampfaCollectionsWorksheet.jrxml
=> CSC-2278: Update imagefilepath to use Medium derivative instead of Thumbnail

services/common/src/main/java/org/collectionspace/services/common/ServiceMain.java
update for ucb_6.0 branch only for version 6.0; main branch is on version 7.1-UCB-10
=> NOJIRA: Bump version build string to UCB-14.rc1

build.xml, cspace-ui/pahma/build.properties, services/common/pom.xml, services/common/src/main/java/org/collectionspace/services/common/ServiceMain.java, services/common/src/main/java/org/collectionspace/services/common/storage/JDBCTools.java, src/main/resources/db/postgresql/upgrade/7.0.0/post-init/01_nagpra-nagprareportfiledgroup.sql, src/main/resources/db/postgresql/upgrade/8.0.0/post-init/02_collectionobject_numberofobjects.sql
Improvements to data migration scripts for UCB, and updates to UI versions.
=> Update data migration scripts.

cspace-ui/cinefiles/build.properties
This just updates the version of the CineFiles UI plugin to the one used in 8.0.
=> CineFiles updates for 8.0

cspace-ui/ucbg/build.properties
This just updates the version of the UCBG UI plugin to the one used in 8.0.
=> UCBG updates for 8.0
